# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

on:
  push:
    branches:
      main
      
name: Maven Package

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11 for Shared Runner
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://github.com/Reis-Silva/devops/actions
    needs: build
    steps:
      - name: Aprovação do Revisor
        run: echo Aprovado pelo Revisor.
